## 源氏、父帝の嫁に手を出す

藤壺の宮[^1]が少しお病気におなりになって宮中から自邸へ退出して来ておいでになった。帝が日々恋しく思召す御様子に源氏は同情しながらも、稀にしかないお実家住まいの機会をとらえないではまたいつ恋しいお顔が見られるかと夢中になって、それ以来どの恋人の所へも行かず宮中の宿直所ででも、二条の院ででも、昼間は終日物思いに暮らして、王命婦[^2]に手引きを迫ることのほかは何もしなかった。王命婦がどんな方法をとったのか与えられた無理なわずかな逢瀬の中にいる時も、幸福が現実の幸福とは思えないで夢としか思われないのが、源氏はみずから残念であった。宮も過去のある夜の思いがけぬ過失の罪悪感が一生忘れられないもののように思っておいでになって、せめてこの上の罪は重ねまいと深く思召したのであるのに、またもこうしたことを他動的に繰り返すことになったのを悲しくお思いになって、恨めしいふうでおありになりながら、柔らかな魅力があって、しかも打ち解けておいでにならない最高の貴女の態度が美しく思われる源氏は、やはりだれよりもすぐれた女性である、なぜ一所でも欠点を持っておいでにならないのであろう、それであれば自分の心はこうして死ぬほどにまで惹かれないで楽であろうと思うと源氏はこの人の存在を自分に知らせた運命さえも恨めしく思われるのである。源氏の恋の万分の一も告げる時間のあるわけはない。永久の夜が欲しいほどであるのに、逢わない時よりも恨めしい別れの時が至った。

[^1]: 源氏の思い人。桐壺の更衣（母）に似ていて、紫の上の縁者。源氏の子（冷泉帝）を生むが、冷泉帝は桐壺帝の皇子として育てられる。のちの三宮と柏木、薫君の関係がこの関係を思い起こすようになっている。自分の父の嫁に手を出す源氏よりは柏木の方が健全な気もするが…。源氏はほぼ常に桐壺帝に可愛がられるが、柏木が源氏に疎まれて亡くなるのもちょっとどうかと思う。

[^2]: 藤壺の宮の侍女。源氏に藤壺の宮への手引きを迫られ、許してしまう。このシーンが冷泉帝誕生の原因となる。

> 見てもまた逢ふ夜 稀なる夢の中にやがてまぎるるわが身ともがな

涙にむせ返って言う源氏の様子を見ると、さすがに宮も悲しくて、

> 世語りに人やつたへん類ひなく憂き身をさめぬ夢になしても

とお言いになった。宮が煩悶しておいでになるのも道理なことで、恋にくらんだ源氏の目にももったいなく思われた。源氏の上着などは王命婦がかき集めて寝室の外へ持ってきた。源氏は二条の院へ帰って泣き寝に一日を暮らした[^3]。手紙を出しても、例のとおり御覧にならぬという王命婦の返事以外には得られないのが非常に恨めしくて、源氏は御所へも出ず二、三日引きこもっていた。これをまた病気のように解釈あそばして帝がお案じになるに違いないと思うともったいなく空恐ろしい気ばかりがされるのであった。

[^3]: 源氏物語では人が泣くシーンが多い。現代人からすると不自然だが、当時は人はすぐ泣いていたのかもしれない。

宮も御自身の運命をお歎きになって煩悶が続き、そのために御病気の経過もよろしくないのである。宮中のお使いが始終来て御所へお帰りになることを促されるのであったが、なお宮は里居を続けておいでになった。宮は実際おからだが悩ましくて、しかもその悩ましさの中に生理的な現象らしいものもあるのを、宮御自身だけには思いあたることがないのではなかった。情けなくて、これで自分は子を産むのであろうかと煩悶をしておいでになった。まして夏の暑い間は起き上がることもできずにお寝みになったきりだった。御妊娠が三月であるから女房たちも気がついてきたようである[^4]。宿命の恐ろしさを宮はお思いになっても、人は知らぬことであったから、こんなに月が重なるまで御内奏もあそばされなかったと皆驚いてささやき合った。宮の御入浴のお世話などもきまってしていた宮の乳母の娘である弁[^5]とか、王命婦とかだけは不思議に思うことはあっても、この二人の間でさえ話し合うべき問題ではなかった。命婦は人間がどう努力しても避けがたい宿命というものの力に驚いていたのである。宮中へは御病気やら物怪やらで気のつくことのおくれたように奏上したはずである。だれも皆そう思っていた。帝はいっそうの熱愛を宮へお寄せになることになって[^6]、以前よりもおつかわしになるお使いの度数の多くなったことも、宮にとっては空恐ろしくお思われになることだった。煩悶の合い間というものがなくなった源氏の中将も変わった夢を見て夢解きを呼んで合わさせてみたが、及びもない、思いもかけぬ占いをした。そして、

[^4]: 若紫の段は数か月の出来事になっている。この前後の場面で時間が春から秋ぐらいまで飛ぶ。

[^5]: 藤壺の宮の女官で乳母の子。「弁」は官職名だと思うがよくわからない。

[^6]: 桐壺帝は気づかず、源氏は気づくあたり、桐壺帝と柏木は気の毒で、源氏はクソだなあ、と思います。

「しかし順調にそこへお達しになろうとするのにはお慎みにならなければならぬ故障が一つございます」

と言った。夢を現実にまざまざ続いたことのように言われて、源氏は恐怖を覚えた。

「私の夢ではないのだ。ある人の夢を解いてもらったのだ。今の占いが真実性を帯びるまではだれにも秘密にしておけ」

とその男に言ったのであるが、源氏はそれ以来、どんなことがおこってくるのかと思っていた。その後に源氏は藤壺の宮の御懐妊を聞いて、そんなことがあの占いの男に言われたことなのではないかと思うと、恋人と自分の間に子が生まれてくるということに若い源氏は昂奮して、以前にもまして言葉を尽くして逢瀬を望むことになったが[^7]、王命婦も宮の御懐妊になって以来、以前に自身が、はげしい恋に身を亡しかねない源氏に同情してとった行為が重大性を帯びていることに気がついて、策をして源氏を宮に近づけようとすることを避けたのである。源氏はたまさかに宮から一行足らずのお返事の得られたこともあるが、それも絶えてしまった。

[^7]: エキセントリック過ぎてちょっとよくわからない感情ですね。源氏物語の登場人物で一番共感できないのは源氏だと思う。しかし、常識人ではストーリーボードを回せないので、このぐらいやり過ぎじゃないと主人公は務まらないのかもしれない。

初秋の七月になって宮は御所へおはいりになった。最愛の方が懐妊されたのであるから、帝のお志はますます藤壺の宮にそそがれるばかりであった。少しお腹がふっくりとなって悪阻の悩みに顔の少しお痩せになった宮のお美しさは、前よりも増したのではないかと見えた。以前もそうであったように帝は明け暮れ藤壺にばかり来ておいでになって、もう音楽の遊びをするのにも適した季節にもなっていたから、源氏の中将をも始終そこへお呼び出しになって、琴や笛の役をお命じになった。物思わしさを源氏は極力おさえていたが、時々には忍びがたい様子もうかがわれるのを、宮もお感じになって、さすがにその人にまつわるものの愁わしさをお覚えになった。
