## 源氏、少女を二条の院に連れ帰る

今日は按察使大納言家へ兵部卿の宮が来ておいでになった。以前よりもずっと邸が荒れて、広くて古い家に小人数でいる寂しさが宮のお心を動かした。

「こんな所にしばらくでも小さい人がいられるものではない。やはり私の邸のほうへつれて行こう。たいしたむずかしい所ではないのだよ。乳母は部屋をもらって住んでいればいいし、女王は何人も若い子がいるからいっしょに遊んでいれば非常にいいと思う」

などとお言いになった。そばへお呼びになった小女王の着物には源氏の衣服の匂いが深く沁んでいた。

「いい匂いだね。けれど着物は古くなっているね」

心苦しく思召す様子だった。

「今までからも病身な年寄りとばかりいっしょにいるから、時々は邸のほうへよこして、母と子の情合いのできるようにするほうがよいと私は言ったのだけれど、絶対的にお祖母さんはそれをおさせにならなかったから、邸のほうでも反感を起こしていた。そしてついにその人が亡くなったからといってつれて行くのは済まないような気もする」

と宮がお言いになる。

「そんなに早くあそばす必要はございませんでしょう。お心細くても当分はこうしていらっしゃいますほうがよろしゅうございましょう。少し物の理解がおできになるお年ごろになりましてからおつれなさいますほうがよろしいかと存じます」

少納言はこう答えていた。

「夜も昼もお祖母様が恋しくて泣いてばかりいらっしゃいまして、召し上がり物なども少のうございます」

とも歎いていた。実際姫君は痩せてしまったが、上品な美しさがかえって添ったかのように見える。

「なぜそんなにお祖母様のことばかりをあなたはお思いになるの、亡くなった人はしかたがないんですよ。お父様がおればいいのだよ」

と宮は言っておいでになった。日が暮れるとお帰りになるのを見て、心細がって姫君が泣くと、宮もお泣きになって、

「なんでもそんなに悲しがってはしかたがない。今日明日にでもお父様の所へ来られるようにしよう」

などと、いろいろになだめて宮はお帰りになった。母も祖母も失った女の将来の心細さなどを女王は思うのでなく、ただ小さい時から片時の間も離れず付き添っていた祖母が死んだと思うことだけが非常に悲しいのである。子供ながらも悲しみが胸をふさいでいる気がして遊び相手はいても遊ぼうとしなかった。それでも昼間は何かと紛れているのであったが、夕方ごろからめいりこんでしまう。こんなことで小さいおからだがどうなるかと思って、乳母も毎日泣いていた。その日源氏の所からは惟光をよこした。

> 伺うはずですが宮中からお召しがあるので失礼します。おかわいそうに拝見した女王さんのことが気になってなりません。

源氏からの挨拶はこれで惟光が代わりの宿直をするわけである。

「困ってしまう。将来だれかと御結婚をなさらなければならない女王様を、これではもう源氏の君が奥様になすったような形をお取りになるのですもの。宮様がお聞きになったら私たちの責任だと言っておしかりになるでしょう」

「ねえ女王様、お気をおつけになって、源氏の君のことは宮様がいらっしゃいました時にうっかり言っておしまいにならないようになさいませね」

と少納言が言っても、小女王は、それが何のためにそうしなければならないかがわからないのである。少納言は惟光の所へ来て、身にしむ話をした。

「将来あるいはそうおなりあそばす運命かもしれませんが、ただ今のところはどうしてもこれは不つりあいなお間柄だと私らは存じますのに、御熱心に御縁組のことをおっしゃるのですもの、御酔興か何かと私どもは思うばかりでございます。今日も宮様がおいでになりまして、女の子だからよく気をつけてお守りをせい、うっかり油断をしていてはいけないなどとおっしゃいました時は、私ども何だか平気でいられなく思われました。昨晩のことなんか思い出すものですから」

などと言いながらも、あまりに歎いて見せては姫君の処女であることをこの人に疑わせることになると用心もしていた。惟光もどんな関係なのかわからない気がした。帰って惟光が報告した話から、源氏はいろいろとその家のことが哀れに思いやられてならないのであったが、形式的には良人らしく一泊したあとであるから、続いて通って行かねばならぬが、それはさすがに躊躇された。酔興な結婚をしたように世間が批評しそうな点もあるので、心がおけて行けないのである[^1]。二条の院へ迎えるのが良策であると源氏は思った。手紙は始終送った。日が暮れると惟光を見舞いに出した。

[^1]: 御簾の中に入り込んで少女を膝に抱いたり、惟光を送り込んだりしておいてどういう感情なんですかね…。

> やむをえぬ用事があって出かけられないのを、私の不誠実さからだとお思いにならぬかと不安です。

などという手紙が書かれてくる。

「宮様[^2]のほうから、にわかに明日迎えに行くと言っておよこしになりましたので、取り込んでおります。長い馴染の古いお邸を離れますのも心細い気のすることと私どもめいめい申し合っております」

[^2]: 冒頭に出てきた兵部卿の宮のこと。父親が迎えに来る方が、（やんごとなき）少年に迎えられるより普通に思うが…。乳母の少納言の保身のために言っているような気もする。

と言葉数も少なく言って、大納言家の女房たちは今日はゆっくりと話し相手になっていなかった。忙しそうに物を縫ったり、何かを仕度したりする様子がよくわかるので、惟光は帰って行った。源氏は左大臣家へ行っていたが、例の夫人は急に出て来て逢おうともしなかったのである。面倒な気がして、源氏は東琴（和琴に同じ）を手すさびに弾いて、「常陸には田をこそ作れ、仇心かぬとや君が山を越え、野を越え雨夜来ませる」という田舎めいた歌詞を、優美な声で歌っていた。惟光が来たというので、源氏は居間へ呼んで様子を聞こうとした。惟光によって、女王が兵部卿の宮邸へ移転する前夜であることを源氏は聞いた。源氏は残念な気がした。宮邸へ移ったあとで、そういう幼い人に結婚を申し込むということも物好きに思われることだろう。小さい人を一人盗んで行ったという批難を受けるほうがまだよい[^3]。確かに秘密の保ち得られる手段を取って二条の院へつれて来ようと源氏は決心した。

[^3]: まだよいかな…？

「明日夜明けにあすこへ行ってみよう。ここへ来た車をそのままにして置かせて、随身を一人か二人仕度させておくようにしてくれ」

という命令を受けて惟光は立った。源氏はそののちもいろいろと思い悩んでいた。人の娘を盗み出した噂の立てられる不名誉も、もう少しあの人が大人で思い合った仲であればその犠牲も自分は払ってよいわけであるが、これはそうでもないのである。父宮に取りもどされる時の不体裁も考えてみる必要があると思ったが、その機会をはずすことはどうしても惜しいことであると考えて、翌朝は明け切らぬ間に出かけることにした。

夫人[^4]は昨夜の気持ちのままでまだ打ち解けてはいなかった。

[^4]: 葵の上のこと。そりゃ打ち解けんでしょ。

「二条の院[^5]にぜひしなければならないことのあったのを私は思い出したから出かけます。用を済ませたらまた来ることにしましょう」

[^5]: 源氏の自宅のこと。歳更けてからは六条の院に移る。[東洞院通と二条通の南西](https://www.google.com/maps/place/%E4%BA%AC%E9%83%BD%E5%BA%9C%E4%BA%AC%E9%83%BD%E5%B8%82+%E6%9D%B1%E6%B4%9E%E9%99%A2%E9%80%9A/@35.0134445,135.7612313,20.56z/data=!4m6!3m5!1s0x60010899e8061f7f:0xb5058a100ad48777!8m2!3d35.0019638!4d135.7610908!16s%2Fg%2F1220fnrx?entry=ttu&g_ep=EgoyMDI1MDQzMC4xIKXMDSoASAFQAw%3D%3D)にあったとされている。今の京都地下鉄・烏丸御池のそばあたりか。道長が住んでいた二条殿がこの場所にあった。

と源氏は不機嫌な妻に告げて、寝室をそっと出たので、女房たちも知らなかった。自身の部屋になっているほうで直衣などは着た。馬に乗せた惟光だけを付き添いにして源氏は大納言家へ来た。門をたたくと何の気なしに下男が門をあけた。車を静かに中へ引き込ませて、源氏の伴った惟光が妻戸をたたいて、しわぶき[^6]をすると、少納言が聞きつけて出て来た。

[^6]: せきばらいのこと。このころの人を呼ぶ合図だったのだろう。

「来ていらっしゃるのです」

と言うと、

「女王様はやすんでいらっしゃいます。どちらから、どうしてこんなにお早く」

と少納言が言う。源氏が人の所へ通って行った帰途だと解釈しているのである。

「宮様のほうへいらっしゃるそうですから、その前にちょっと一言お話をしておきたいと思って」

と源氏が言った。

「どんなことでございましょう。まあどんなに確かなお返辞がおできになりますことやら」

少納言は笑っていた。源氏が室内へはいって行こうとするので、この人は当惑したらしい。

「不行儀に女房たちがやすんでおりまして」

「まだ女王さんはお目ざめになっていないのでしょうね。私がお起こししましょう。もう朝霧がいっぱい降る時刻だのに、寝ているというのは」

と言いながら寝室へはいる源氏を少納言は止めることもできなかった。源氏は無心によく眠っていた姫君を抱き上げて目をさまさせた。女王は父宮がお迎えにおいでになったのだと、まだまったくさめない心では思っていた。髪を撫でて直したりして、

「さあ、いらっしゃい。宮様のお使いになって私が来たのですよ」

と言う声を聞いた時に姫君は驚いて、恐ろしく思うふうに見えた。

「いやですね。私だって宮様だって同じ人ですよ。鬼などであるものですか[^7]」

[^7]: 鬼の方がましでは…。

源氏の君が姫君をかかえて出て来た。少納言と、惟光と、外の女房とが、

「あ、どうなさいます」

と同時に言った。

「ここへは始終来られないから、気楽な所へお移ししようと言ったのだけれど、それには同意をなさらないで、ほかへお移りになることになったから、そちらへおいでになってはいろいろ面倒だから、それでなのだ。だれか一人ついておいでなさい」

こう源氏の言うのを聞いて少納言はあわててしまった。

「今日では非常に困るかと思います。宮様がお迎えにおいでになりました節、何とも申し上げようがないではございませんか。ある時間がたちましてから、ごいっしょにおなりになる御縁があるものでございましたら自然にそうなることでございましょう。まだあまりに御幼少でいらっしゃいますから。ただ今そんなことは皆の者の責任になることでございますから」

と言うと、

「じゃいい[^8]。今すぐについて来られないのなら、人はあとで来るがよい」

[^8]: 無茶苦茶なんだよなあ…。暴君にもほどがある。仕えたくない上司ですね。

こんなふうに言って源氏は車を前へ寄せさせた。姫君も怪しくなって泣き出した。少納言は止めようがないので、昨夜縫った女王の着物を手にさげて、自身も着がえをしてから車に乗った。

二条の院は近かったから、まだ明るくならないうちに着いて、西の対に車を寄せて降りた[^9]。源氏は姫君を軽そうに抱いて降ろした。

[^9]: ココで無理矢理紫の上を連れ帰ってしまうわけですね。控えめに言っても現代人には理解できない。

「夢のような気でここまでは参りましたが、私はどうしたら」

少納言は下車するのを躊躇した。

「どうでもいいよ。もう女王さんがこちらへ来てしまったのだから、君だけ帰りたければ送らせよう」

源氏が強かった。しかたなしに少納言も降りてしまった。このにわかの変動に先刻から胸が鳴り続けているのである。宮が自分をどうお責めになるだろうと思うことも苦労の一つであった。それにしても姫君はどうなっておしまいになる運命なのであろうと思って、ともかくも母や祖母に早くお別れになるような方は紛れもない不幸な方であることがわかると思うと、涙がとめどなく流れそうであったが、しかもこれが姫君の婚家へお移りになる第一日であると思うと、縁起悪く泣くことは遠慮しなくてはならないと努めていた。

ここは平生あまり使われない御殿であったから帳台なども置かれてなかった。源氏は惟光を呼んで帳台、屏風などをその場所場所に据えさせた。これまで上へあげて掛けてあった几帳の垂れ絹はおろせばいいだけであったし、畳の座なども少し置き直すだけで済んだのである。東の対へ夜着類を取りにやって寝た。姫君は恐ろしがって、自分をどうするのだろうと思うと慄えが出るのであったが、さすがに声を立てて泣くことはしなかった。

「少納言の所で私は寝るのよ」

子供らしい声で言う。

「もうあなたは乳母などと寝るものではありませんよ」

と源氏が教えると、悲しがって泣き寝をしてしまった。乳母は眠ることもできず、ただむやみに泣かれた。
