## 源氏、尼が亡くなったのを聞き、少女の御簾に入り込む

この十月に朱雀院へ行幸があるはずだった。その日の舞楽[^1]には貴族の子息たち、高官、殿上役人などの中の優秀な人が舞い人に選ばれていて、親王方、大臣をはじめとして音楽の素養の深い人はそのために新しい稽古を始めていた。それで源氏の君も多忙であった。北山の寺へも久しく見舞わなかったことを思って、ある日わざわざ使いを立てた。山からは僧都の返事だけが来た。

[^1]: 足利義満の時代から能が舞台芸術の中心になったが、この頃は[舞楽](https://www2.nhk.or.jp/school/watch/clip/?das_id=D0005310192_00000)が中心。[渡来系の舞](https://www2.ntj.jac.go.jp/dglib/contents/learn/edc22/naritachi/bugaku/index.html)として、現代でも皇室や神社に残る。

> 先月の二十日にとうとう姉は亡くなりまして、これが人生の掟であるのを承知しながらも悲しんでおります。

源氏は今さらのように人間の生命の脆さが思われた。尼君が気がかりでならなかったらしい小女王はどうしているだろう。小さいのであるから、祖母をどんなに恋しがってばかりいることであろうと想像しながらも、自身の小さくて母に別れた悲哀も確かに覚えないなりに思われるのであった。源氏からは丁寧な弔慰品が山へ贈られたのである。そんな場合にはいつも少納言が行き届いた返事を書いて来た。

尼君の葬式のあとのことが済んで、一家は京の邸へ帰って来ているということであったから、それから少しあとに源氏は自身で訪問した。凄いように荒れた邸に小人数で暮らしているのであったから、小さい人などは怖しい気がすることであろうと思われた。以前の座敷へ迎えて少納言が泣きながら哀れな若草を語った。源氏も涙のこぼれるのを覚えた。

「宮様のお邸へおつれになることになっておりますが、お母様の御生前にいろんな冷酷なことをなさいました奥さま[^2]がいらっしゃるのでございますから、それがいっそずっとお小さいとか、また何でもおわかりになる年ごろになっていらっしゃるとかすればいいのでございますが、中途半端なお年で、おおぜいお子様のいらっしゃる中で軽い者にお扱われになることになってはと、尼君も始終それを苦労になさいましたが、宮様のお内のことを聞きますと、まったく取り越し苦労でなさそうなんでございますから、あなた様のお気まぐれからおっしゃってくださいますことも、遠い将来にまでにはたとえどうなりますにしましても、お救いの手に違いないと私どもは思われますが、奥様になどとは想像も許されませんようなお子供らしさでございまして、普通のあの年ごろよりももっともっと赤様なのでございます」

[^2]: 兵部卿の正妻。尼の娘を疎んじていた。この頃は女性が家の中心で、財政を預かっていたはずなのだが（だから源氏は女性宅を訪ねまくっている）、収入等がどうなっていたのかよくわからない。

と少納言が言った。

「そんなことはどうでもいいじゃありませんか、私が繰り返し繰り返しこれまで申し上げてあることをなぜ無視しようとなさるのですか。その幼稚な方を私が好きでたまらないのは、こればかりは前生の縁に違いない[^3]と、それを私が客観的に見ても思われます。許してくだすって、この心持ちを直接女王さんに話させてくださいませんか。

[^3]: 言い草もちょっと意味がわかりませんね…。源氏の心意気はよくわからない。

> あしわかの[^4]浦にみるめは難くともこは立ちながら帰る波かは

[^4]: 葦の若い葉のこと。若紫がつらい境遇にあるのに帰るのはつらいと言っているのだと思う。

私をお見くびりになってはいけません」

源氏がこう言うと、

「それはもうほんとうにもったいなく思っているのでございます。

> 寄る波の心も知らで和歌の浦[^5]に玉藻なびかんほどぞ浮きたる

[^5]: [和歌山市街から紀三井寺の間の浦](https://wakanoura-nihonisan.jp/)のこと。

このことだけは御信用ができませんけれど」

物馴れた少納言の応接のしように、源氏は何を言われても不快には思われなかった。「年を経てなど越えざらん逢坂の関[^6]」という古歌を口ずさんでいる源氏の美音に若い女房たちは酔ったような気持ちになっていた。女王は今夜もまた祖母を恋しがって泣いていた時に、遊び相手の童女が、

[^6]: 京都市内（今の山科）と大津の間の関のこと。ずいぶんと昔から関が築かれており、和歌にもよく登場する。

「直衣[^7]を着た方が来ていらっしゃいますよ。宮様が来ていらっしゃるのでしょう」

[^7]: のうし。皇族や上位の公家が着ていた服装。

と言ったので、起きて来て、

「少納言、直衣着た方どちら、宮様なの」

こう言いながら乳母のそばへ寄って来た声がかわいかった。これは父宮ではなかったが、やはり深い愛を小女王に持つ源氏であったから、心がときめいた。

「こちらへいらっしゃい」

と言ったので、父宮でなく源氏の君であることを知った女王は、さすがにうっかりとしたことを言ってしまったと思うふうで、乳母のそばへ寄って、

「さあ行こう。私は眠いのだもの」

と言う。

「もうあなたは私に御遠慮などしないでもいいんですよ。私の膝の上へお寝みなさい」

と源氏が言った。

「お話しいたしましたとおりでございましょう。こんな赤様なのでございます」

乳母に源氏のほうへ押し寄せられて、女王はそのまま無心にすわっていた。源氏が御簾の下から手を入れて探ってみると柔らかい着物の上に、ふさふさとかかった端の厚い髪が手に触れて美しさが思いやられるのである。手をとらえると、父宮でもない男性の近づいてきたことが恐ろしくて、

「私、眠いと言っているのに」

と言って手を引き入れようとするのについて源氏は御簾の中へはいって来た。

「もう私だけがあなたを愛する人なんですよ。私をお憎みになってはいけない」

源氏はこう言っている。少納言が、

「よろしくございません。たいへんでございます。お話しになりましても何の効果もございませんでしょうのに」

と困ったように言う。

「いくら何でも私はこの小さい女王さんを情人にしようとはしない。まあ私がどれほど誠実であるかを御覧なさい」

外には霙[^8]が降っていて凄い夜である。

[^8]: みぞれ。みぞれの降る夜に少女を訪ね、無理矢理に膝に乗せる男。事案ですね。

「こんなに小人数でこの寂しい邸にどうして住めるのですか」

と言って源氏は泣いていた。捨てて帰って行けない気がするのであった。

「もう戸をおろしておしまいなさい。こわいような夜だから、私が宿直[^9]の男になりましょう。女房方は皆女王さんの室へ来ていらっしゃい」

[^9]: とのい。宿直の警備員みたいなもの。

と言って、馴れたことのように女王さんを帳台の中へ抱いてはいった。だれもだれも意外なことにあきれていた。乳母は心配をしながらも普通の闖入者を扱うようにはできぬ相手に歎息をしながら控えていた。小女王は恐ろしがってどうするのかと慄えているので肌も毛穴が立っている。かわいく思う源氏はささやかな異性を単衣に巻きくるんで、それだけを隔てに寄り添っていた。この所作がわれながら是認しがたいものとは思いながらも愛情をこめていろいろと話していた。

「ねえ、いらっしゃいよ、おもしろい絵がたくさんある家で、お雛様遊びなんかのよくできる私の家へね」

こんなふうに小さい人の気に入るような話をしてくれる源氏の柔らかい調子に、姫君は恐ろしさから次第に解放されていった。しかし不気味であることは忘れずに、眠り入ることはなくて身じろぎしながら寝ていた。この晩は夜通し風が吹き荒れていた。

「ほんとうにお客様がお泊まりにならなかったらどんなに私たちは心細かったでしょう。同じことなら女王様がほんとうの御結婚のできるお年であればね」

などと女房たちはささやいていた。心配でならない乳母は帳台の近くに侍していた。風の少し吹きやんだ時はまだ暗かったが、帰る源氏はほんとうの恋人のもとを別れて行く情景に似ていた。

「かわいそうな女王さんとこんなに親しくなってしまった以上[^10]、私はしばらくの間もこんな家へ置いておくことは気がかりでたまらない。私の始終住んでいる家へお移ししよう。こんな寂しい生活をばかりしていらっしゃっては女王さんが神経衰弱におなりになるから」

[^10]: 疵物になるから、ということでしょうか？この段の源氏の感情は無茶苦茶すぎてよくわからない。

と源氏が言った。

「宮様もそんなにおっしゃいますが、あちらへおいでになることも、四十九日が済んでからがよろしかろうと存じております」

「お父様のお邸ではあっても、小さい時から別の所でお育ちになったのだから、私に対するお気持ちと親密さはそう違わないでしょう。今からいっしょにいることが将来の障りになるようなことは断じてない。私の愛が根底の深いものになるだけだと思う」

と女王の髪を撫でながら源氏は言って顧みながら去った。深く霧に曇った空も艶であって、大地には霜が白かった。ほんとうの恋の忍び歩きにも適した朝の風景であると思うと、源氏は少し物足りなかった。近ごろ隠れて通っている人の家[^11]が途中にあるのを思い出して、その門をたたかせたが内へは聞こえないらしい。しかたがなくて供の中から声のいい男を選んで歌わせた。

[^11]: ここも誰のことを指すのかわからない。前触れぐらいは出していたのだと思うが…。女児に会っていて行けませんでした、とは言えないなあ。

> 朝ぼらけ霧立つ空の迷ひにも行き過ぎがたき妹が門かな

二度繰り返させたのである。気のきいたふうをした下仕えの女中を出して、

> 立ちとまり霧の籬[^12]の過ぎうくば草の戸ざしに障りしもせじ

[^12]: まがき。垣根のこと。

と言わせた。女はすぐに門へはいってしまった。それきりだれも出て来ないので、帰ってしまうのも冷淡な気がしたが、夜がどんどん明けてきそうで、きまりの悪さに二条の院へ車を進めさせた。

かわいかった小女王を思い出して、源氏は独り笑みをしながら又寝をした。朝おそくなって起きた源氏は手紙をやろうとしたが、書く文章も普通の恋人扱いにはされないので、筆を休め休め考えて書いた。よい絵なども贈った。
