## 源氏、尼と少女の身元を僧都に尋ねる

寺で皆が寝床についていると、僧都の弟子が訪問して来て、惟光に逢いたいと申し入れた。狭い場所であったから惟光へ言う事が源氏にもよく聞こえた。

「手前どもの坊の奥の寺へおいでになりましたことを人が申しますのでただ今承知いたしました。すぐに伺うべきでございますが、私がこの山におりますことを御承知のあなた様が素通りをあそばしたのは、何かお気に入らないことがあるかと御遠慮をする心もございます。御宿泊の設けも行き届きませんでも当坊でさせていただきたいものでございます」

と言うのが使いの伝える僧都の挨拶だった。

「今月の十幾日ごろから私は瘧病にかかっておりましたが、たびたびの発作で堪えられなくなりまして、人の勧めどおりに山へ参ってみましたが、もし効験が見えませんでした時には一人の僧の不名誉になることですから、隠れて来ておりました。そちらへも後刻伺うつもりです」

と源氏は惟光に言わせた。それから間もなく僧都が訪問して来た。尊敬される人格者で、僧ではあるが貴族出のこの人に軽い旅装で逢うことを源氏はきまり悪く思った。二年越しの山籠りの生活を僧都は語ってから、

「僧の家というものはどうせ皆寂しい貧弱なものですが、ここよりは少しきれいな水の流れなども庭にはできておりますから、お目にかけたいと思うのです」

僧都は源氏の来宿を乞うてやまなかった。源氏を知らないあの女の人たちにたいそうな顔の吹聴などをされていたことを思うと、しりごみもされるのであるが、心を惹いた少女のことも詳しく知りたいと思って源氏は僧都の坊へ移って行った。主人の言葉どおりに庭の作り一つをいってもここは優美な山荘であった、月はないころであったから、流れのほとりに篝を焚かせ、燈籠を吊らせなどしてある。南向きの室を美しく装飾して源氏の寝室ができていた。奥の座敷から洩れてくる薫香のにおいと仏前に焚かれる名香の香が入り混じって漂っている山荘に、新しく源氏の追い風が加わったこの夜を女たちも晴れがましく思った。

僧都は人世の無常さと来世の頼もしさを源氏に説いて聞かせた。源氏は自身の罪の恐ろしさが自覚され、来世で受ける罰の大きさを思うと、そうした常ない人生から遠ざかったこんな生活に自分もはいってしまいたいなどと思いながらも、夕方に見た小さい貴女が心にかかって恋しい源氏であった。

「ここへ来ていらっしゃるのはどなたなんですか、その方たちと自分とが因縁のあるというような夢を私は前に見たのですが、なんだか今日こちらへ伺って謎の糸口を得た気がします」

と源氏が言うと、

「突然な夢のお話ですね。それがだれであるかをお聞きになっても興がおさめになるだけでございましょう。前の按察使大納言はもうずっと早く亡くなったのでございますからご存じはありますまい。その夫人が私の姉です。未亡人になってから尼になりまして、それがこのごろ病気なものですから、私が山にこもったきりになっているので心細がってこちらへ来ているのです」

僧都の答えはこうだった。

「その大納言にお嬢さんがおありになるということでしたが、それはどうなすったのですか。私は好色から伺うのじゃありません、まじめにお尋ね申し上げるのです」

少女は大納言の遺子であろうと想像して源氏が言うと、

「ただ一人娘がございました。亡くなりましてもう十年余りになりますでしょうか、大納言は宮中へ入れたいように申して、非常に大事にして育てていたのですがそのままで死にますし、未亡人が一人で育てていますうちに、だれがお手引きをしたのか兵部卿の宮[^1]が通っていらっしゃるようになりまして、それを宮の御本妻はなかなか権力のある夫人で、やかましくお言いになって、私の姪はそんなことからいろいろ苦労が多くて、物思いばかりをしたあげく亡くなりました。物思いで病気が出るものであることを私は姪を見てよくわかりました」

[^1]: 紫の上の父で藤壺の宮の兄。尼の娘は正妻ではなかったため、正妻（宮の御本妻）から疎まれており、兵部卿の宮は尼の娘や紫の上とは疎遠だった。後々このことで兵部卿の宮が源氏に疎まれることに。

などと僧都は語った。それではあの少女は昔の按察使大納言[^2]の姫君と兵部卿の宮の間にできた子であるに違いないと源氏は悟ったのである。藤壺の宮の兄君の子であるがためにその人に似ているのであろうと思うといっそう心の惹かれるのを覚えた。身分のきわめてよいのがうれしい、愛する者を信じようとせずに疑いの多い女でなく、無邪気な子供を、自分が未来の妻として教養を与えていくことは楽しいことであろう、それを直ちに実行したいという心に源氏はなった。

[^2]: 尼の夫で紫の上の母方の祖父。この時点ではすでに亡くなっている。

「お気の毒なお話ですね。その方には忘れ形見がなかったのですか」

なお明確に少女のだれであるかを知ろうとして源氏は言うのである。

「亡くなりますころに生まれました。それも女です。その子供が姉の信仰生活を静かにさせません。姉は年を取ってから一人の孫娘の将来ばかりを心配して暮らしております」

聞いている話に、夕方見た尼君の涙を源氏は思い合わせた。

「妙なことを言い出すようですが、私にその小さいお嬢さんを、託していただけないかとお話ししてくださいませんか。私は妻について一つの理想がありまして、ただ今結婚はしていますが、普通の夫婦生活なるものは私に重荷に思えまして、まあ独身もののような暮らし方ばかりをしているのです[^3]。まだ年がつり合わぬなどと常識的に判断をなすって、失礼な申し出だと思召すでしょうか」
と源氏は言った。

[^3]: 17～18歳の青年の言い草とは考えにくいセリフ。今の妻は理想ではないらしい。かと言って若嫁を育てようとはならないのでは。

「それは非常に結構なことでございますが、まだまだとても幼稚なものでございますから、仮にもお手もとへなど迎えていただけるものではありません。まあ女というものは良人のよい指導を得て一人前になるものなのですから、あながち早過ぎるお話とも何とも私は申されません。子供の祖母と相談をいたしましてお返辞をするといたしましょう」

こんなふうにてきぱき言う人が僧形の厳めしい人であるだけ、若い源氏には恥ずかしくて、望んでいることをなお続けて言うことができなかった。

「阿弥陀様がいらっしゃる堂で用事のある時刻になりました。初夜の勤めがまだしてございません。済ませましてまた」

こう言って僧都は御堂のほうへ行った。
