## 源氏、尼の見舞いに行き、少女の声を聴く

北山へ養生に行っていた按察使大納言の未亡人[^1]は病が快くなって京へ帰って来ていた。源氏は惟光などに京の家を訪ねさせて時々手紙などを送っていた。先方の態度は春も今も変わったところがないのである。それも道理に思えることであったし、またこの数月間というものは、過去の幾年間にもまさった恋の煩悶が源氏にあって、ほかのことは何一つ熱心にしようとは思われないのでもあったりして、より以上積極性を帯びていくようでもなかった。

[^1]: 紫の上の祖母、尼のこと。

秋の末になって、恋する源氏は心細さを人よりも深くしみじみと味わっていた。ある月夜にある女[^2]の所を訪ねる気にやっとなった源氏が出かけようとするとさっと時雨がした。源氏の行く所は六条の京極辺であったから、御所から出て来たのではやや遠い気がする。荒れた家の庭の木立ちが大家らしく深いその土塀の外を通る時に、例の傍去らずの惟光が言った。

[^2]: 誰に会いに行っているのかよくわからない。六条御息所の邸宅で、後の源氏の邸宅である六条院は六条京極、今の[京都市地下鉄・五条駅と京阪；清水五条の間](https://blog.goo.ne.jp/kakitutei/e/dc193621e4fef7e29ca61513a4dd0c53)ぐらいにあったらしい。なので、この女性は六条御息所だと思われる。

「これが前の按察使大納言の家[^3]でございます。先日ちょっとこの近くへ来ました時に寄ってみますと、あの尼さんからは、病気に弱ってしまっていまして、何も考えられませんという挨拶がありました」

[^3]: 二条の院（東洞院通と二条通の南西）から六条院（京阪・清水五条）の間にあったはず。女の子を無理矢理連れ帰るのは難しくなさそうですね…。

「気の毒だね。見舞いに行くのだった。なぜその時にそう言ってくれなかったのだ。ちょっと私が訪問に来たがと言ってやれ」

源氏がこう言うので惟光は従者の一人をやった。この訪問が目的で来たと最初言わせたので、そのあとでまた惟光がはいって行って、

「主人が自身でお見舞いにおいでになりました」

と言った。大納言家では驚いた。

「困りましたね。近ごろは以前よりもずっと弱っていらっしゃるから、お逢いにはなれないでしょうが、お断わりするのはもったいないことですから」

などと女房は言って、南向きの縁座敷をきれいにして源氏を迎えたのである。

「見苦しい所でございますが、せめて御厚志のお礼を申し上げませんではと存じまして、思召しでもございませんでしょうが、こんな部屋などにお通しいたしまして」

という挨拶を家の者がした。そのとおりで、意外な所へ来ているという気が源氏にはした。

「いつも御訪問をしたく思っているのでしたが、私のお願いをとっぴなものか何かのようにこちらではお扱いになるので、きまりが悪かったのです。それで自然御病気もこんなに進んでいることを知りませんでした」

と源氏が言った。

「私は病気であることが今では普通なようになっております。しかしもうこの命の終わりに近づきましたおりから、かたじけないお見舞いを受けました喜びを自分で申し上げません失礼をお許しくださいませ。あの話は今後もお忘れになりませんでしたら、もう少し年のゆきました時にお願いいたします。一人ぼっちになりますあの子に残る心が、私の参ります道の障りになることかと思われます」

取り次ぎの人に尼君が言いつけている言葉が隣室であったから、その心細そうな声も絶え絶え聞こえてくるのである。

「失礼なことでございます。孫がせめてお礼を申し上げる年になっておればよろしいのでございますのに」

とも言う。源氏は哀れに思って聞いていた。

「今さらそんな御挨拶はなさらないでください。通り一遍な考えでしたなら、風変わりな酔狂者と誤解されるのも構わずに、こんな御相談は続けません。どんな前生の因縁でしょうか、女王さんをちょっとお見かけいたしました時から、女王さんのことをどうしても忘れられないようなことになりましたのも不思議なほどで[^4]、どうしてもこの世界だけのことでない、約束事としか思われません」

[^4]: 見舞いも忘れて、ここ数か月は藤壺の宮のことで思い悩んでいただけなのになあ…。

などと源氏は言って、また、

「自分を理解していただけない点で私は苦しんでおります。あの小さい方が何か一言お言いになるのを伺えればと思うのですが」

と望んだ。

「それは姫君は何もご存じなしに、もうお寝みになっていまして」

女房がこんなふうに言っている時に、向こうからこの隣室へ来る足音がして、

「お祖母様、あのお寺にいらっしった源氏の君が来ていらっしゃるのですよ。なぜ御覧にならないの」

と女王は言った。女房たちは困ってしまった。

「静かにあそばせよ」

と言っていた。

「でも源氏の君を見たので病気がよくなったと言っていらしたからよ」

自分の覚えているそのことが役に立つ時だと女王は考えている。源氏はおもしろく思って聞いていたが、女房たちの困りきったふうが気の毒になって、聞かない顔をして、まじめな見舞いの言葉を残して去った。子供らしい子供らしいというのはほんとうだ、けれども自分はよく教えていける気がすると源氏は思ったのであった。

翌日もまた源氏は尼君へ丁寧に見舞いを書いて送った。例のように小さくしたほうの手紙には、

> いはけなき[^5]鶴の一声聞きしより葦間になづむ船ぞえならぬ

[^5]: 幼い。聞かない顔をして後からこういう便りを送るのはどうかと思いますね…。

> いつまでも一人の人を対象にして考えているのですよ。

わざわざ子供にも読めるふうに書いた源氏のこの手紙の字もみごとなものであったから、そのまま姫君の習字の手本にしたらいいと女房らは言った。源氏の所へ少納言が返事を書いてよこした。

> お見舞いくださいました本人は、今日も危いようでございまして、ただ今から皆で山の寺へ移ってまいるところでございます。

> かたじけないお見舞いのお礼はこの世界で果たしませんでもまた申し上げる時がございましょう。

というのである。秋の夕べはまして人の恋しさがつのって、せめてその人に縁故のある少女を得られるなら得たいという望みが濃くなっていくばかりの源氏であった。「消えん空なき」と尼君の歌った晩春の山の夕べに見た面影が思い出されて恋しいとともに、引き取って幻滅を感じるのではないかと危ぶむ心も源氏にはあった。

> 手に摘みていつしかも見ん紫の根に通ひける野辺の若草

このころの源氏の歌である。
